// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roadmap.Api.Data;

#nullable disable

namespace Roadmap.Api.Migrations
{
    [DbContext(typeof(RoadmapDbContext))]
    [Migration("20260326065626_Latest")]
    partial class Latest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Roadmap.Api.Entities.CustomLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId", "Date");

                    b.ToTable("custom_logs", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.DayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId", "Date")
                        .IsUnique();

                    b.ToTable("day_plans", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.DayPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DayPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("DayPlanId", "StartMinute");

                    b.ToTable("day_plan_entries", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.HabitCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SprintHabitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SprintHabitId", "Date")
                        .IsUnique();

                    b.ToTable("habit_checks", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.NodeCategoryLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NodeId", "CategoryId")
                        .IsUnique();

                    b.ToTable("node_category_links", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.RelaxDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId", "Date")
                        .IsUnique();

                    b.ToTable("relax_days", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.RoadmapDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("roadmaps", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.RoadmapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlockSortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PointsPerUnit")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleBlockId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleTemplate")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("NotStarted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double?>("TotalSize")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("UnitsPerHour")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ScheduleBlockId", "BlockSortOrder");

                    b.HasIndex("RoadmapId", "ParentId", "SortOrder");

                    b.ToTable("roadmap_nodes", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.ScheduleBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleTemplate")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId", "SortOrder");

                    b.ToTable("schedule_blocks", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SingleTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DelayedUntil")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<double>("EstimatedHours")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Weekdays")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId", "IsCompleted", "Priority");

                    b.ToTable("single_tasks", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RelaxDays")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId", "StartDate");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<double>("TargetAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SprintId", "SortOrder");

                    b.ToTable("sprint_goals", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintGoalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("SprintGoalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SprintGoalId", "Date");

                    b.ToTable("sprint_goal_logs", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintHabit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("SprintId", "HabitId")
                        .IsUnique();

                    b.ToTable("sprint_habits", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<double>("PlannedUnits")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("SprintId", "Date");

                    b.ToTable("sprint_plan_entries", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.StatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("RoadmapId", "NodeId", "ChangedAt");

                    b.ToTable("status_changes", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.WeekPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId", "WeekStart")
                        .IsUnique();

                    b.ToTable("week_plans", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.WeekPlanGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("ResultAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("ResultNote")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SprintGoalId")
                        .HasColumnType("uuid");

                    b.Property<double?>("TargetAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("TargetDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("WeekPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SprintGoalId");

                    b.HasIndex("WeekPlanId", "SortOrder");

                    b.ToTable("week_plan_goals", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.WorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("RoadmapId", "NodeId", "Date");

                    b.HasIndex("SprintId", "NodeId", "Date")
                        .IsUnique();

                    b.ToTable("work_logs", (string)null);
                });

            modelBuilder.Entity("Roadmap.Api.Entities.CustomLog", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.DayPlan", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.DayPlanEntry", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.DayPlan", "DayPlan")
                        .WithMany("Entries")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.RoadmapNode", "Node")
                        .WithMany("DayPlanEntries")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayPlan");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.Habit", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.HabitCheck", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.SprintHabit", "SprintHabit")
                        .WithMany("Checks")
                        .HasForeignKey("SprintHabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintHabit");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.NodeCategoryLink", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapNode", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.RoadmapNode", "Node")
                        .WithMany("CategoryLinks")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.RelaxDay", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.RoadmapNode", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany("Nodes")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.ScheduleBlock", "ScheduleBlock")
                        .WithMany("Items")
                        .HasForeignKey("ScheduleBlockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");

                    b.Navigation("Roadmap");

                    b.Navigation("ScheduleBlock");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.ScheduleBlock", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SingleTask", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.Sprint", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintGoal", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintGoalLog", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.SprintGoal", "SprintGoal")
                        .WithMany("Logs")
                        .HasForeignKey("SprintGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintGoal");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintHabit", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.Habit", "Habit")
                        .WithMany("SprintHabits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintPlanEntry", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.Sprint", "Sprint")
                        .WithMany("PlanEntries")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.StatusChange", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapNode", "Node")
                        .WithMany("StatusChanges")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.WeekPlan", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.WeekPlanGoal", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.SprintGoal", "SprintGoal")
                        .WithMany()
                        .HasForeignKey("SprintGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Roadmap.Api.Entities.WeekPlan", "WeekPlan")
                        .WithMany("CustomGoals")
                        .HasForeignKey("WeekPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintGoal");

                    b.Navigation("WeekPlan");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.WorkLog", b =>
                {
                    b.HasOne("Roadmap.Api.Entities.RoadmapNode", "Node")
                        .WithMany("WorkLogs")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.RoadmapDefinition", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roadmap.Api.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Roadmap");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.DayPlan", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.Habit", b =>
                {
                    b.Navigation("SprintHabits");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.RoadmapDefinition", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.RoadmapNode", b =>
                {
                    b.Navigation("CategoryLinks");

                    b.Navigation("Children");

                    b.Navigation("DayPlanEntries");

                    b.Navigation("StatusChanges");

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.ScheduleBlock", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.Sprint", b =>
                {
                    b.Navigation("PlanEntries");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintGoal", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.SprintHabit", b =>
                {
                    b.Navigation("Checks");
                });

            modelBuilder.Entity("Roadmap.Api.Entities.WeekPlan", b =>
                {
                    b.Navigation("CustomGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
